name: Build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - 'learn\/*'
    paths-ignore:
      - '**/**.md'

permissions:
  id-token: write
  contents: read

jobs:
  set_infrastructure_job:
    name: Set resources
    uses: ./.github/workflows/set-resources.yml
    secrets: inherit

  code_job:
    name: Build and deploy code
    needs: set_infrastructure_job
    uses: ./.github/workflows/build-deploy-code.yml
    with:
      staticSiteApiToken: ${{ needs.set_infrastructure_job.outputs.staticSiteApiToken }}
    secrets: inherit

  # close_pull_request_job:
  #   if: github.event_name == 'pull_request' && github.event.action == 'closed'
  #   runs-on: ubuntu-latest
  #   name: Close Pull Request Job
  #   steps:
  #     - name: Close Pull Request
  #       id: closepullrequest
  #       uses: Azure/static-web-apps-deploy@v1
  #       with:
  #         azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
  #         action: "close"
